### ISSUE TITLE
Storage increases when the second cell is running

### ISSUE THREAD

**Issue by qianzhangut** [ResidentChief/simple_a1111_paperspace#3]
Hi ResidentChief,

THanks for your great work. I download all the models in tmp folder, but when I run the second cell, the storage still increases to x gigabytes. Looks like the stable diffusion webui folder is installing all the required files (most are in venv folder). Any way to avoid this happen?

`root@s4rx2ybaesb:/notebooks/stable-diffusion-webui/venv/lib/python3.9/site-packages# du -schc  
5.5G   `

**Comment by donaldanixon** [comment]
The venv installs into /notebooks/stable-diffusion-webui so you don't have to install everything (as in the whole python environment) from scratch each time - should be about 6gb.

You could edit the runbook to do the git clone into /tmp as well, but then everything has to download each time, which will take longer.

**Comment by qianzhangut** [comment]
Thanks [ResidentChief](https://github.com/ResidentChief). Appreciate your help!
